// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIh5dqPFIr1eOfD-6R8ihma0gszE5I2fY',
    appId: '1:546932262559:web:156e464adcb968ce95c4aa',
    messagingSenderId: '546932262559',
    projectId: 'events-4939f',
    authDomain: 'events-4939f.firebaseapp.com',
    storageBucket: 'events-4939f.appspot.com',
    measurementId: 'G-9Y0091YVN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA33NxH3ZvYws_DUuPLhJSobLAt8Uwn2do',
    appId: '1:546932262559:android:9a6f52528a76a67f95c4aa',
    messagingSenderId: '546932262559',
    projectId: 'events-4939f',
    storageBucket: 'events-4939f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxwthMnQmwylaswGTTG3SIzv9kias7UNY',
    appId: '1:546932262559:ios:1728f2499de4930695c4aa',
    messagingSenderId: '546932262559',
    projectId: 'events-4939f',
    storageBucket: 'events-4939f.appspot.com',
    iosClientId: '546932262559-a2vdi0finhk0g0fklgt40qtm378ojspi.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgetGenius',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxwthMnQmwylaswGTTG3SIzv9kias7UNY',
    appId: '1:546932262559:ios:1728f2499de4930695c4aa',
    messagingSenderId: '546932262559',
    projectId: 'events-4939f',
    storageBucket: 'events-4939f.appspot.com',
    iosClientId: '546932262559-a2vdi0finhk0g0fklgt40qtm378ojspi.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgetGenius',
  );
}
